const {
    REACT_APP_API_URL,
    REACT_APP_NAME,
    REACT_APP_CRYPTO_STORAGE_KEY,
    REACT_APP_VIEWPORTWIDTH,
    REACT_APP_VERSION,
    REACT_APP_THEME_COLOR,
} = process.env;

const API_URL = REACT_APP_API_URL;
const ADMIN_NAME = REACT_APP_NAME;
const CRYPTO_STORAGE_KEY = REACT_APP_CRYPTO_STORAGE_KEY;
const VIEWPORTWIDTH = REACT_APP_VIEWPORTWIDTH;
const VERSION = REACT_APP_VERSION;
const THEME_COLOR = REACT_APP_THEME_COLOR;

export {
    API_URL,
    ADMIN_NAME,
    CRYPTO_STORAGE_KEY,
    VIEWPORTWIDTH,
    VERSION,
    THEME_COLOR,
};
